### User signup endpoint
POST http://localhost:8090/v1/user
Content-Type: application/json

{
    "name": "Zackvfdxgd",
    "company": "Zavien tecvxvxh",
    "address": "New York, USA",
    "phone": "876765654564",
    "email": "phillips@gmail.com",
    "password": "phillips123"
}

### User signin endpoint
POST http://localhost:8090/v1/user/login
Content-Type: application/json

{    
    "email": "phillips@gmail.com",
    "password": "phillips1234"
}

### Get User profile endpoint
GET http://localhost:8090/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InppZGFuZUBnbWFpbC5jb20iLCJpYXQiOjE2NDA1MTMyNjcsImV4cCI6MTY0MDUxMzMyN30.Cn4_XzRcU8TLsmRvhUylxNXze7UCHqWOQho3dWtHnlk

### Token routers

### Get refreshed token
GET http://localhost:8090/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InppZGFuZUBnbWFpbC5jb20iLCJpYXQiOjE2NDA1MTMyNjcsImV4cCI6MTY0MzEwNTI2N30.U-seqRajubQA6vtVlYd8fblzxNrDp70Jt0GsaFKwqoY

### Password Reset Endpoint
POST http://localhost:8090/v1/user/reset-password
Content-Type: application/json

{    
    "email": "phillips@gmail.com"
}

### Update New password Endpoint
PATCH http://localhost:8090/v1/user/reset-password
Content-Type: application/json

{    
    "email": "phillips@gmail.com",
    "pin": 980884,
    "newPassword": "phillips1234"
}
